---
deployment:
  tasks:
    - export DEPLOYPATH=/home/knowledge/todolisttodolist.knowledge-fort.com
    - /bin/cp * $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH 
    # -R For Directories , * is for all